- name: "Install Java"
  yum: 
    name: java-1.8.0-openjdk
    state: present

- name: "Install jenkins"
  yum:
    name: jenkins

- name: Start jenkins server
  service:
    name: jenkins
    state: started
    enabled: yes