- hosts: sandbox
  become: yes
  become_user: root
  tasks:
  roles:
    - hostname
    - unix_groups
    - unix_users
    - httpd
    - {role: sudoers/allow-all, group_name: group_a}
    - {role: sudoers/allow-httpd, group_name: group_b}
    - jenkins
    - cron/yum_autoupdate
    - samples/shell

- hosts: ec2-sandbox
  become: yes
  become_user: root
  vars:
    - ansible_distribution_major_version: 7
  tasks:
  roles:
    - hostname
    - unix_groups
    - unix_users
    - httpd
    - {role: sudoers/allow-all, group_name: group_a}
    - {role: sudoers/allow-httpd, group_name: group_b}
    - jenkins
    - cron/yum_autoupdate
    - samples/shell
    - role: geerlingguy.mysql
      mysql_root_password: hogehoge
      mysql_databases:
        - name: l4a_db
          encoding: utf8
          collation: utf8_unicode_ci
        - name: guestbook
          encoding: utf8
          collation: utf8_unicode_ci 
      mysql_users:
        - name: l4a_user
          host: "%"
          password: fugafuga
          priv: "l4a_db.*:ALL"
        - name: guestbook
          host: "%"
          password: guestbookpass
          priv: "guestbook.*:ALL"
    - php
    - git
    - role: php-guestbook
      db_host: localhost
      db_name: guestbook
      db_user: guestbook
      db_pass: guestbookpass
      tags: deploy
